// Initial Seed Data for Smart Canteen Management System

export const INITIAL_CATEGORIES = [
  { id: 'all', name: 'All Items', icon: 'Sparkles' },
  { id: 'breakfast', name: 'Morning Breakfast', icon: 'Croissant' },
  { id: 'meals', name: 'Afternoon Lunch', icon: 'Utensils' },
  { id: 'dinner', name: 'Night Dinner', icon: 'Moon' },
  { id: 'snacks', name: 'Snacks & Quick Bites', icon: 'Sandwich' },
  { id: 'beverages', name: 'Beverages', icon: 'Coffee' },
  { id: 'desserts', name: 'Desserts', icon: 'CakeSlice' },
  { id: 'combos', name: 'Smart Combos', icon: 'Flame' },
];

export const INITIAL_MENU_ITEMS = [
  // --- MORNING BREAKFAST ITEMS ---
  {
    id: 'item_4',
    name: 'South Indian Masala Dosa',
    category: 'breakfast',
    price: 55,
    isVeg: true,
    mealTime: 'morning',
    description: 'Crispy golden fermented crepe stuffed with spiced potato mash, served with piping hot sambar & coconut chutney.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80',
    preparation_time: 7,
    rating: 4.8,
    rating_count: 420,
    availability: 'available',
    isPopular: true,
    calories: '310 kcal',
    ingredients: [
      { name: 'Dosa Batter', qty: 100, unit: 'ml' },
      { name: 'Potatoes & Onions', qty: 60, unit: 'g' },
    ],
  },
  {
    id: 'item_13',
    name: 'Steaming Idli Sambar (3 Pcs)',
    category: 'breakfast',
    price: 45,
    isVeg: true,
    mealTime: 'morning',
    description: 'Ultra-soft steamed rice cakes paired with aromatic vegetable sambar and freshly ground coconut chutney.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    preparation_time: 4,
    rating: 4.9,
    rating_count: 510,
    availability: 'available',
    isPopular: true,
    calories: '220 kcal',
    ingredients: [
      { name: 'Dosa Batter', qty: 120, unit: 'ml' },
      { name: 'Veggies & Lettuce', qty: 40, unit: 'g' },
    ],
  },
  {
    id: 'item_14',
    name: 'Indori Poha with Crispy Sev',
    category: 'breakfast',
    price: 35,
    isVeg: true,
    mealTime: 'morning',
    description: 'Light flattened rice tempered with mustard seeds, curry leaves, turmeric, topped with pomegranate seeds and spicy Ratlami sev.',
    image: 'https://images.unsplash.com/photo-1613292443284-8d10ef9383fe?w=600&auto=format&fit=crop&q=80',
    preparation_time: 3,
    rating: 4.7,
    rating_count: 390,
    availability: 'available',
    isPopular: false,
    calories: '240 kcal',
    ingredients: [
      { name: 'Potatoes & Onions', qty: 50, unit: 'g' },
    ],
  },
  {
    id: 'item_15',
    name: 'Stuffed Aloo Paratha with Curd & Pickle',
    category: 'breakfast',
    price: 50,
    isVeg: true,
    mealTime: 'morning',
    description: 'Whole wheat flatbread filled with spiced mashed potatoes, roasted with butter, served with chilled yogurt and mango pickle.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80',
    preparation_time: 8,
    rating: 4.9,
    rating_count: 640,
    availability: 'available',
    isPopular: true,
    calories: '380 kcal',
    ingredients: [
      { name: 'Wheat Paratha', qty: 1, unit: 'pcs' },
      { name: 'Potatoes & Onions', qty: 80, unit: 'g' },
      { name: 'Milk & Dairy', qty: 50, unit: 'ml' },
    ],
  },

  // --- AFTERNOON LUNCH ITEMS ---
  {
    id: 'item_6',
    name: 'North Indian Thali Deluxe',
    category: 'meals',
    price: 110,
    isVeg: true,
    mealTime: 'afternoon',
    description: 'Complete balanced lunch with Paneer Butter Masala, Dal Makhani, 2 Butter Rotis, Jeera Rice, Salad, and Gulab Jamun.',
    image: 'https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?w=600&auto=format&fit=crop&q=80',
    preparation_time: 14,
    rating: 4.8,
    rating_count: 380,
    availability: 'available',
    isPopular: true,
    calories: '720 kcal',
    ingredients: [
      { name: 'Basmati Rice', qty: 100, unit: 'g' },
      { name: 'Paneer (Cottage Cheese)', qty: 60, unit: 'g' },
      { name: 'Wheat Paratha', qty: 2, unit: 'pcs' },
    ],
  },
  {
    id: 'item_3',
    name: 'Special Chicken Dum Biryani',
    category: 'meals',
    price: 130,
    isVeg: false,
    mealTime: 'afternoon',
    description: 'Slow-cooked aromatic basmati rice infused with saffron, layered with tender marinated chicken pieces and boiled egg.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
    preparation_time: 12,
    rating: 4.9,
    rating_count: 680,
    availability: 'available',
    isPopular: true,
    calories: '650 kcal',
    ingredients: [
      { name: 'Basmati Rice', qty: 150, unit: 'g' },
      { name: 'Chicken', qty: 120, unit: 'g' },
      { name: 'Spices & Ghee', qty: 25, unit: 'g' },
    ],
  },
  {
    id: 'item_16',
    name: 'Homestyle Rajma Chawal Bowl',
    category: 'meals',
    price: 80,
    isVeg: true,
    mealTime: 'afternoon',
    description: 'Slow-simmered Punjabi red kidney beans in rich tomato-onion gravy poured over fragrant steamed basmati rice with pickled onions.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80',
    preparation_time: 6,
    rating: 4.9,
    rating_count: 590,
    availability: 'available',
    isPopular: true,
    calories: '490 kcal',
    ingredients: [
      { name: 'Basmati Rice', qty: 140, unit: 'g' },
      { name: 'Potatoes & Onions', qty: 60, unit: 'g' },
    ],
  },

  // --- NIGHT DINNER ITEMS ---
  {
    id: 'item_17',
    name: 'Butter Paneer & Garlic Naan Platter',
    category: 'dinner',
    price: 125,
    isVeg: true,
    mealTime: 'night',
    description: 'Creamy tomato-cashew makhani gravy with soft paneer cubes, served with 2 freshly baked butter garlic naans and salad.',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&auto=format&fit=crop&q=80',
    preparation_time: 12,
    rating: 4.9,
    rating_count: 480,
    availability: 'available',
    isPopular: true,
    calories: '680 kcal',
    ingredients: [
      { name: 'Paneer (Cottage Cheese)', qty: 90, unit: 'g' },
      { name: 'Wheat Paratha', qty: 2, unit: 'pcs' },
      { name: 'Milk & Dairy', qty: 40, unit: 'ml' },
    ],
  },
  {
    id: 'item_18',
    name: 'Schezwan Egg Fried Rice & Manchurian',
    category: 'dinner',
    price: 110,
    isVeg: false,
    mealTime: 'night',
    description: 'Wok-tossed spicy schezwan fried rice with scrambled eggs and garden veggies, served with tangy vegetable Manchurian gravy.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80',
    preparation_time: 10,
    rating: 4.8,
    rating_count: 520,
    availability: 'available',
    isPopular: true,
    calories: '590 kcal',
    ingredients: [
      { name: 'Basmati Rice', qty: 130, unit: 'g' },
      { name: 'Cooking Oil', qty: 20, unit: 'ml' },
    ],
  },
  {
    id: 'item_19',
    name: 'Late-Night Double Cheese Maggi & Cold Coffee',
    category: 'dinner',
    price: 85,
    isVeg: true,
    mealTime: 'night',
    description: 'Classic campus favorite: Spicy butter-fried Maggi noodles with molten cheddar cheese layer paired with chilled chocolate cold coffee.',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&auto=format&fit=crop&q=80',
    preparation_time: 6,
    rating: 5.0,
    rating_count: 1120,
    availability: 'available',
    isPopular: true,
    calories: '510 kcal',
    ingredients: [
      { name: 'Milk & Dairy', qty: 150, unit: 'ml' },
      { name: 'Coffee & Tea', qty: 10, unit: 'g' },
    ],
  },
  {
    id: 'item_20',
    name: 'Chicken Shawarma Plate with Pita & Hummus',
    category: 'dinner',
    price: 135,
    isVeg: false,
    mealTime: 'night',
    description: 'Spit-roasted sliced chicken thigh marinated with Lebanese spices, served with fluffy pita bread, garlic toum, and pickled veggies.',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&auto=format&fit=crop&q=80',
    preparation_time: 11,
    rating: 4.9,
    rating_count: 730,
    availability: 'few_left',
    isPopular: true,
    calories: '610 kcal',
    ingredients: [
      { name: 'Chicken', qty: 130, unit: 'g' },
      { name: 'Burger Buns', qty: 1, unit: 'pcs' },
    ],
  },

  // --- SNACKS & FAST FOOD ---
  {
    id: 'item_1',
    name: 'Crispy Veg Burger',
    category: 'snacks',
    price: 60,
    isVeg: true,
    mealTime: 'all',
    description: 'Crispy seasoned vegetable patty layered with fresh lettuce, sliced tomatoes & creamy herb mayo in toasted sesame bun.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80',
    preparation_time: 8,
    rating: 4.8,
    rating_count: 342,
    availability: 'available',
    isPopular: true,
    calories: '380 kcal',
    ingredients: [
      { name: 'Burger Buns', qty: 1, unit: 'pcs' },
      { name: 'Veg Patty', qty: 1, unit: 'pcs' },
      { name: 'Veggies & Lettuce', qty: 50, unit: 'g' },
    ],
  },
  {
    id: 'item_2',
    name: 'Paneer Tikka Roll',
    category: 'snacks',
    price: 75,
    isVeg: true,
    mealTime: 'all',
    description: 'Char-grilled cottage cheese cubes marinated in tandoori spices, rolled in flaky paratha with mint chutney and crunchy onions.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80',
    preparation_time: 10,
    rating: 4.9,
    rating_count: 512,
    availability: 'few_left',
    isPopular: true,
    calories: '420 kcal',
    ingredients: [
      { name: 'Paneer (Cottage Cheese)', qty: 80, unit: 'g' },
      { name: 'Wheat Paratha', qty: 1, unit: 'pcs' },
      { name: 'Mint Chutney', qty: 20, unit: 'g' },
    ],
  },
  {
    id: 'item_5',
    name: 'Peri-Peri French Fries',
    category: 'snacks',
    price: 50,
    isVeg: true,
    mealTime: 'all',
    description: 'Golden fried crispy potato fingers tossed in spicy peri-peri dust, served with tangy garlic dip.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80',
    preparation_time: 6,
    rating: 4.6,
    rating_count: 290,
    availability: 'available',
    isPopular: false,
    calories: '280 kcal',
    ingredients: [
      { name: 'Potatoes & Onions', qty: 120, unit: 'g' },
      { name: 'Cooking Oil', qty: 30, unit: 'ml' },
    ],
  },
  {
    id: 'item_10',
    name: 'Grilled Chicken Sub Sandwich',
    category: 'snacks',
    price: 90,
    isVeg: false,
    mealTime: 'all',
    description: 'Herb-marinated sliced chicken breast, chipotle sauce, cheddar cheese slice, fresh bell peppers on multiseed sub.',
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600&auto=format&fit=crop&q=80',
    preparation_time: 9,
    rating: 4.7,
    rating_count: 275,
    availability: 'available',
    isPopular: false,
    calories: '440 kcal',
    ingredients: [
      { name: 'Chicken', qty: 100, unit: 'g' },
      { name: 'Burger Buns', qty: 1, unit: 'pcs' },
      { name: 'Veggies & Lettuce', qty: 40, unit: 'g' },
    ],
  },

  // --- BEVERAGES ---
  {
    id: 'item_7',
    name: 'Iced Cold Coffee with Ice Cream',
    category: 'beverages',
    price: 45,
    isVeg: true,
    mealTime: 'all',
    description: 'Blended espresso with chilled milk and chocolate drizzle, crowned with a scoop of vanilla ice cream.',
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&auto=format&fit=crop&q=80',
    preparation_time: 4,
    rating: 4.9,
    rating_count: 750,
    availability: 'available',
    isPopular: true,
    calories: '210 kcal',
    ingredients: [
      { name: 'Milk & Dairy', qty: 180, unit: 'ml' },
      { name: 'Coffee & Tea', qty: 15, unit: 'g' },
    ],
  },
  {
    id: 'item_11',
    name: 'Fresh Lemon Mint Cooler',
    category: 'beverages',
    price: 30,
    isVeg: true,
    mealTime: 'all',
    description: 'Refreshing thirst quencher made with freshly squeezed lemons, crushed mint leaves, rock salt & chilled sparkling soda.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    preparation_time: 3,
    rating: 4.6,
    rating_count: 180,
    availability: 'available',
    isPopular: false,
    calories: '85 kcal',
    ingredients: [
      { name: 'Veggies & Lettuce', qty: 20, unit: 'g' },
    ],
  },

  // --- DESSERTS ---
  {
    id: 'item_9',
    name: 'Hot Chocolate Brownie Sundae',
    category: 'desserts',
    price: 65,
    isVeg: true,
    mealTime: 'all',
    description: 'Warm fudgy walnut brownie served on a sizzler plate with vanilla scoop, molten hot fudge and roasted nuts.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    preparation_time: 5,
    rating: 4.9,
    rating_count: 310,
    availability: 'available',
    isPopular: false,
    calories: '450 kcal',
    ingredients: [
      { name: 'Milk & Dairy', qty: 50, unit: 'ml' },
      { name: 'Bakery Desserts', qty: 1, unit: 'pcs' },
    ],
  },

  // --- COMBOS ---
  {
    id: 'item_8',
    name: 'Masala Chai & Samosa Duo',
    category: 'combos',
    price: 35,
    isVeg: true,
    mealTime: 'morning',
    description: 'Steaming ginger-cardamom cutting chai paired with two crispy triangular potato samosas & sweet chutney.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80',
    preparation_time: 5,
    rating: 4.9,
    rating_count: 820,
    availability: 'few_left',
    isPopular: true,
    calories: '290 kcal',
    ingredients: [
      { name: 'Potatoes & Onions', qty: 80, unit: 'g' },
      { name: 'Coffee & Tea', qty: 10, unit: 'g' },
      { name: 'Milk & Dairy', qty: 100, unit: 'ml' },
    ],
  },
  {
    id: 'item_12',
    name: 'Student Power Combo (Burger + Fries + Coke)',
    category: 'combos',
    price: 120,
    isVeg: true,
    mealTime: 'all',
    description: 'Value pack: 1 Crispy Veg Burger + 1 Medium Peri-Peri Fries + 1 Chilled Beverage. Campus favorite saver!',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=600&auto=format&fit=crop&q=80',
    preparation_time: 11,
    rating: 4.9,
    rating_count: 940,
    availability: 'available',
    isPopular: true,
    calories: '690 kcal',
    ingredients: [
      { name: 'Burger Buns', qty: 1, unit: 'pcs' },
      { name: 'Veg Patty', qty: 1, unit: 'pcs' },
      { name: 'Potatoes & Onions', qty: 100, unit: 'g' },
    ],
  }
];

export const INITIAL_INVENTORY = [
  { id: 'inv_1', name: 'Burger Buns', quantity: 45, minimum_stock: 20, unit: 'pcs', category: 'Bakery', lastRestocked: 'Today 08:00 AM' },
  { id: 'inv_2', name: 'Veg Patty', quantity: 38, minimum_stock: 15, unit: 'pcs', category: 'Frozen', lastRestocked: 'Yesterday' },
  { id: 'inv_3', name: 'Paneer (Cottage Cheese)', quantity: 4.5, minimum_stock: 3.0, unit: 'kg', category: 'Dairy', lastRestocked: 'Today 07:30 AM' },
  { id: 'inv_4', name: 'Chicken', quantity: 8.2, minimum_stock: 5.0, unit: 'kg', category: 'Poultry', lastRestocked: 'Today 07:00 AM' },
  { id: 'inv_5', name: 'Basmati Rice', quantity: 24.0, minimum_stock: 10.0, unit: 'kg', category: 'Grains', lastRestocked: '2 days ago' },
  { id: 'inv_6', name: 'Potatoes & Onions', quantity: 18.0, minimum_stock: 8.0, unit: 'kg', category: 'Vegetables', lastRestocked: 'Today 08:00 AM' },
  { id: 'inv_7', name: 'Veggies & Lettuce', quantity: 3.2, minimum_stock: 2.0, unit: 'kg', category: 'Vegetables', lastRestocked: 'Today 08:00 AM' },
  { id: 'inv_8', name: 'Wheat Paratha', quantity: 12, minimum_stock: 15, unit: 'pcs', category: 'Bakery', lastRestocked: 'Yesterday', alert: true },
  { id: 'inv_9', name: 'Milk & Dairy', quantity: 14.0, minimum_stock: 5.0, unit: 'L', category: 'Dairy', lastRestocked: 'Today 07:30 AM' },
  { id: 'inv_10', name: 'Coffee & Tea', quantity: 2.1, minimum_stock: 1.0, unit: 'kg', category: 'Dry Goods', lastRestocked: '3 days ago' },
  { id: 'inv_11', name: 'Cooking Oil', quantity: 15.0, minimum_stock: 6.0, unit: 'L', category: 'Grocery', lastRestocked: '4 days ago' },
  { id: 'inv_12', name: 'Bakery Desserts', quantity: 8, minimum_stock: 10, unit: 'pcs', category: 'Bakery', lastRestocked: 'Yesterday', alert: true },
];

export const INITIAL_USER = {
  id: 'usr_varsha',
  name: 'Varsha Sharma',
  studentId: 'CS-2024-8842',
  email: 'varsha.sharma@campus.edu',
  phone: '+91 98765 43210',
  role: 'student',
  dietaryPreference: 'vegetarian',
  walletBalance: 450,
  preferredCategories: ['snacks', 'beverages', 'combos'],
  recentOrdersCount: 14,
  avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
};

export const INITIAL_ORDERS = [
  {
    order_id: 'ORD-1024',
    token_number: 'A124',
    user_id: 'usr_varsha',
    customer_name: 'Varsha Sharma',
    student_id: 'CS-2024-8842',
    items: [
      { item_id: 'item_1', name: 'Crispy Veg Burger', quantity: 2, price: 60, image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80' },
      { item_id: 'item_7', name: 'Iced Cold Coffee with Ice Cream', quantity: 1, price: 45, image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&auto=format&fit=crop&q=80' },
    ],
    total_amount: 165,
    pickup_time: '1:30 PM',
    payment_status: 'PAID (Campus Card)',
    order_status: 'preparing', // placed | accepted | preparing | ready | collected | cancelled
    counter: 'Counter 2',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
    prep_time_min: 8,
    queue_position: 2,
  },
  {
    order_id: 'ORD-1023',
    token_number: 'A123',
    user_id: 'usr_varsha',
    customer_name: 'Varsha Sharma',
    student_id: 'CS-2024-8842',
    items: [
      { item_id: 'item_4', name: 'South Indian Masala Dosa', quantity: 1, price: 55, image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=80' },
      { item_id: 'item_8', name: 'Masala Chai & Samosa Duo', quantity: 1, price: 35, image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80' },
    ],
    total_amount: 90,
    pickup_time: '10:45 AM',
    payment_status: 'PAID (Campus Card)',
    order_status: 'collected',
    counter: 'Counter 1',
    created_at: new Date(Date.now() - 120 * 60000).toISOString(),
    prep_time_min: 7,
    queue_position: 0,
  },
  {
    order_id: 'ORD-1022',
    token_number: 'A122',
    user_id: 'usr_varsha',
    customer_name: 'Varsha Sharma',
    student_id: 'CS-2024-8842',
    items: [
      { item_id: 'item_6', name: 'North Indian Thali Deluxe', quantity: 1, price: 110, image: 'https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?w=600&auto=format&fit=crop&q=80' },
    ],
    total_amount: 110,
    pickup_time: '1:15 PM',
    payment_status: 'PAID (UPI)',
    order_status: 'collected',
    counter: 'Counter 2',
    created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
    prep_time_min: 14,
    queue_position: 0,
  }
];

export const INITIAL_FEEDBACKS = [
  {
    feedback_id: 'fb_1',
    user_name: 'Varsha Sharma',
    token: 'A123',
    rating: 5,
    food_rating: 5,
    service_rating: 5,
    comment: 'The breakfast Masala Dosa was piping hot and the AI pickup recommendation saved me 10 mins during morning break!',
    time: 'Today, 10:50 AM',
    sentiment: 'positive',
  },
  {
    feedback_id: 'fb_2',
    user_name: 'Aman Patel',
    token: 'A118',
    rating: 4,
    food_rating: 5,
    service_rating: 4,
    comment: 'Delicious Paneer Roll. Counter 1 was slightly busy but digital token tracking kept me updated.',
    time: 'Today, 11:15 AM',
    sentiment: 'positive',
  },
  {
    feedback_id: 'fb_3',
    user_name: 'Priya Nair',
    token: 'A112',
    rating: 3,
    food_rating: 4,
    service_rating: 3,
    comment: 'Food quality was great, though 1:15 PM slot had a small 3-minute queue due to a sudden break crowd.',
    time: 'Yesterday, 1:40 PM',
    sentiment: 'neutral',
  },
];
